### PR TITLE
Port GOQLFilter to gramps60 by vendoring gramps-object-query-language

### PR DESCRIPTION
**Pull request by dsblank**
## What GOQLFilter provides

GOQLFilter brings GOQL (`gramps-object-query-language`) — the same query language and compiler [gramps-web-api](https://github.com/gramps-project/gramps-web-api) uses for its fast, SQL-pushed-down object-query endpoints, and that Gramps Connect's advanced search box speaks — into Gramps Desktop, as a matched pair of filter rules and gramplets for every primary object type (Person, Family, Event, Place, Repository, Source, Citation, Media, Note). (Note: this is distinct from GQL, the separate query language used in Gramps Web's own advanced search.)

- **GUI command-line completion.** A Tab-triggered, live-filtering autocomplete popup offers column names, relationship names (`father`, `birth`, ...), collection names (`children`, `events`, ...), where-expression keywords (`and`/`or`/`not`/`in`/`like`/`Date`/`exists`/`count`), and comparison operators as you type — the same shape as a REPL's completion, not a picker widget.
- **Color syntax highlighting.** Each token (keyword/string/number/operator/known-constant-class) is classified and colored live as you type, from the same shared vocabulary the completion source uses so the two can't drift apart.
- **Fast, SQL-based queries.** A typed expression compiles through the `gramps_object_query_language` compiler to a where-AST, evaluated via `evaluate_where()` — the identical engine gramps-web-api pushes down to SQL server-side, here running locally against the open tree.
- **Reusable as an ordinary Custom Filter.** "Define filter" hands the same expression to Gramps' own `EditFilter` dialog as a single `MatchesExpression` rule, so it can be named and saved like any other Custom Filter, not just used inline in the gramplet.

In short: this is the desktop-side counterpart to the GOQL search box already available in Gramps Connect — same expression language, same underlying compiler — now available as native GTK gramplets and filter rules in Gramps Desktop.

## Summary

Ports the [GOQLFilter](https://github.com/gramps-project/addons-source/tree/maintenance/gramps61/GOQLFilter) addon (currently only on `maintenance/gramps61`) to Gramps 6.0, so the GOQL where-expression filter rules/gramplets are available there too.

The gramps61 branch depends on `pip install gramps-object-query-language` (via `requires_mod`). That's unreliable across Gramps 6.0's various AIO installers, so this branch instead vendors a copy of the library directly:

- `GOQLFilter/gramps_object_query_language_copy/` — a verbatim copy of the `gramps-object-query-language` PyPI package (pinned at v0.4.0), imported under this renamed package so it can never collide with a real pip-installed copy of the same library on the same interpreter. Its `__init__.py` documents the pinned version/commit and how to refresh it.
- Every internal import of `gramps_object_query_language.*` (in `goql.py`, `whereexprrule.py`, `goql_completion.py`, `goql_highlight.py`, and the integration test) repointed to `gramps_object_query_language_copy.*`.
- `requires_mod=["gramps_object_query_language"]` dropped from both `.gpr.py` files (9 rule registrations + 9 gramplet registrations) — nothing left to `pip install`.
- `gramps_target_version` bumped from `"6.1"` down to `"6.0"`.

## Test plan

- [x] Vendored copy imports standalone and `compile_expr()`/`evaluate_where()` work.
- [x] End-to-end: built an in-memory local sqlite Gramps db with two `Person` objects, compiled a where-expression, ran `evaluate_where()` against the real objects — correct match/non-match.
- [x] All 8 addon source files import for real (not just parse) outside the GTK-dependent paths.
- [x] `pytest tests/test_goql_highlight.py tests/test_goql_completion.py tests/test_integration_whereexprrule.py` → 29 passed.
- [ ] `test_goql.py` / `test_goql_completion_popup.py` (GTK-dependent) not exercised here — blocked locally by an unrelated GTK-version conflict in the dev environment, not by this change.
- [x] Manual smoke test inside a real Gramps 6.0 GUI (install via addon manager / drop into a plugin dir, confirm the gramplets and filter rules show up and work) — not yet done.

Co-Authored-By: Claude Sonnet 5 <noreply@anthropic.com>
https://claude.ai/code/session_017Wzor7k5iGEe8bwxkS8zBZ

### CODE REVIEW

**Comment by dsblank** [comment]
@GaryGriffin this version is separate from gramps61 version.

**Comment by GaryGriffin** [comment]
Are you missing a MANIFEST?

Tried on 6.0.6 Mac and got:

```
gary$ Gramps6.0.6.app/Contents/MacOS/Gramps
2026-08-31 17:32:19.348: WARNING: _manager.py: line 328: Plugin error (from 'whereexprrule'): No module named 'gramps_object_query_language_copy'
2026-08-31 17:32:19.349: WARNING: _manager.py: line 328: Plugin error (from 'whereexprrule'): No module named 'gramps_object_query_language_copy'
2026-08-31 17:32:19.349: WARNING: _manager.py: line 328: Plugin error (from 'whereexprrule'): No module named 'gramps_object_query_language_copy'
2026-08-31 17:32:19.349: WARNING: _manager.py: line 328: Plugin error (from 'whereexprrule'): No module named 'gramps_object_query_language_copy'
2026-08-31 17:32:19.349: WARNING: _manager.py: line 328: Plugin error (from 'whereexprrule'): No module named 'gramps_object_query_language_copy'
2026-08-31 17:32:19.349: WARNING: _manager.py: line 328: Plugin error (from 'whereexprrule'): No module named 'gramps_object_query_language_copy'
2026-08-31 17:32:19.350: WARNING: _manager.py: line 328: Plugin error (from 'whereexprrule'): No module named 'gramps_object_query_language_copy'
2026-08-31 17:32:19.350: WARNING: _manager.py: line 328: Plugin error (from 'whereexprrule'): No module named 'gramps_object_query_language_copy'
2026-08-31 17:32:19.350: WARNING: _manager.py: line 328: Plugin error (from 'whereexprrule'): No module named 'gramps_object_query_language_copy'
2026-08-31 17:32:19.350: WARNING: _manager.py: line 328: Plugin error (from 'whereexprrule'): No module named 'gramps_object_query_language_copy'
2026-08-31 17:32:19.350: WARNING: _manager.py: line 328: Plugin error (from 'whereexprrule'): No module named 'gramps_object_query_language_copy'
2026-08-31 17:32:19.350: WARNING: _manager.py: line 328: Plugin error (from 'whereexprrule'): No module named 'gramps_object_query_language_copy'
2026-08-31 17:32:19.351: WARNING: _manager.py: line 328: Plugin error (from 'whereexprrule'): No module named 'gramps_object_query_language_copy'
2026-08-31 17:32:19.351: WARNING: _manager.py: line 328: Plugin error (from 'whereexprrule'): No module named 'gramps_object_query_language_copy'
2026-08-31 17:32:19.351: WARNING: _manager.py: line 328: Plugin error (from 'whereexprrule'): No module named 'gramps_object_query_language_copy'
2026-08-31 17:32:19.351: WARNING: _manager.py: line 328: Plugin error (from 'whereexprrule'): No module named 'gramps_object_query_language_copy'
2026-08-31 17:32:19.351: WARNING: _manager.py: line 328: Plugin error (from 'whereexprrule'): No module named 'gramps_object_query_language_copy'
2026-08-31 17:32:19.354: WARNING: _manager.py: line 328: Plugin error (from 'goql'): No module named 'gramps_object_query_language_copy'
```

**Comment by dsblank** [comment]
Thanks! Fixed, and we may have to expand the section on MANIFEST in AGENTS.md to be a bit more precise.

**Comment by GaryGriffin** [comment]
Gramplet works on Mac 6.0.6
Ran unittests - integration failed, the rest passed. Is this expected?

```
python3 -m unittest GOQLFilter.tests.test_integration_whereexprrule

(python3 -m unittest:45598): Gdk-WARNING **: 20:00:15.006: Failed to initialize CVDisplayLink!
E......E..E..
======================================================================
ERROR: test_optimizer_recognizes_selected_handles (GOQLFilter.tests.test_integration_whereexprrule.SqlPushDownTest.test_optimizer_recognizes_selected_handles)
Regression test for the actual ~8s "Apply time" bug: the
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Volumes/Storage/Development/addons-source/GOQLFilter/tests/test_integration_whereexprrule.py", line 257, in test_optimizer_recognizes_selected_handles
    handles_in, handles_out = optimizer.compute_potential_handles_for_rule(rule)
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'Optimizer' object has no attribute 'compute_potential_handles_for_rule'

======================================================================
ERROR: test_empty_expression_matches_nothing (GOQLFilter.tests.test_integration_whereexprrule.WhereExprRuleTest.test_empty_expression_matches_nothing)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Volumes/Storage/Development/addons-source/GOQLFilter/tests/test_integration_whereexprrule.py", line 140, in test_empty_expression_matches_nothing
    matched = self._apply_person_filter("")
  File "/Volumes/Storage/Development/addons-source/GOQLFilter/tests/test_integration_whereexprrule.py", line 122, in _apply_person_filter
    return set(gfilter.apply(cdb, self.db.get_person_handles()))
               ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/GrampsTest/gtk/inst/lib/python3.13/site-packages/gramps/gen/filters/_genericfilter.py", line 295, in apply
    res = self.apply_logical_op_to_all(
        db, id_list, apply_logical_op, user, tupleind, tree
    )
  File "/Users/GrampsTest/gtk/inst/lib/python3.13/site-packages/gramps/gen/filters/_genericfilter.py", line 147, in apply_logical_op_to_all
    optimizer = Optimizer(self)
  File "/Users/GrampsTest/gtk/inst/lib/python3.13/site-packages/gramps/gen/filters/optimizer.py", line 57, in __init__
    self.walk_filters(filter, False, self.all_selected_handles)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/GrampsTest/gtk/inst/lib/python3.13/site-packages/gramps/gen/filters/optimizer.py", line 82, in walk_filters
    rules_with_selected_handles.append(set(item.selected_handles))
                                       ~~~^^^^^^^^^^^^^^^^^^^^^^^
TypeError: 'NoneType' object is not iterable

======================================================================
ERROR: test_invalid_expression_matches_nothing_rather_than_raising (GOQLFilter.tests.test_integration_whereexprrule.WhereExprRuleTest.test_invalid_expression_matches_nothing_rather_than_raising)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Volumes/Storage/Development/addons-source/GOQLFilter/tests/test_integration_whereexprrule.py", line 144, in test_invalid_expression_matches_nothing_rather_than_raising
    matched = self._apply_person_filter("this is not valid GOQL !!")
  File "/Volumes/Storage/Development/addons-source/GOQLFilter/tests/test_integration_whereexprrule.py", line 122, in _apply_person_filter
    return set(gfilter.apply(cdb, self.db.get_person_handles()))
               ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/GrampsTest/gtk/inst/lib/python3.13/site-packages/gramps/gen/filters/_genericfilter.py", line 295, in apply
    res = self.apply_logical_op_to_all(
        db, id_list, apply_logical_op, user, tupleind, tree
    )
  File "/Users/GrampsTest/gtk/inst/lib/python3.13/site-packages/gramps/gen/filters/_genericfilter.py", line 147, in apply_logical_op_to_all
    optimizer = Optimizer(self)
  File "/Users/GrampsTest/gtk/inst/lib/python3.13/site-packages/gramps/gen/filters/optimizer.py", line 57, in __init__
    self.walk_filters(filter, False, self.all_selected_handles)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/GrampsTest/gtk/inst/lib/python3.13/site-packages/gramps/gen/filters/optimizer.py", line 82, in walk_filters
    rules_with_selected_handles.append(set(item.selected_handles))
                                       ~~~^^^^^^^^^^^^^^^^^^^^^^^
TypeError: 'NoneType' object is not iterable

----------------------------------------------------------------------
Ran 13 tests in 0.503s

FAILED (errors=3)
```

**Comment by dsblank** [comment]
Claude says:

---

Not expected as an addon bug — this points to a mismatch between the actual Gramps build installed on the Mac and the real v6.0.6 source.

What's happening: All three integration failures trace into Gramps core's gen/filters/optimizer.py, not into whereexprrule.py. I compared the traceback against this repo's local gramps checkout at tags v6.0.5/v6.0.6/v6.0.7 — they all contain the current Optimizer (compute_potential_handles_for_filter/compute_potential_handles_for_rule, hasattr(rule, "selected_handles") → returns rule.selected_handles as-is, None included).

But the traceback from the Mac run shows a completely different, older implementation: Optimizer.__init__ calling self.walk_filters(...), with rules_with_selected_handles.append(set(item.selected_handles)). That code only exists in commit 1280aa45a5 ("Refactor, fix, and optimize filters/rules", 2025‑02‑03) — it was replaced by two later fixes, be30d5e715 (2025‑06‑09, "Fix Optimizer class when combining sub-filters") and 18df2e9893 (2025‑08‑10, "Fix the problem of mixed filter types"), both of which landed before v6.0.6 was actually tagged (2025‑11‑08).

Conclusion: whereexprrule.py is written correctly against the current (fixed) Gramps optimizer API — that's exactly what the addon's own docstring/regression test documents. The Mac's installed "Gramps 6.0.6" (path /Users/GrampsTest/gtk/inst/... suggests a custom/dev build) is running an optimizer.py that predates two upstream bugfixes, despite reporting itself as 6.0.6. I'd have the user check what's actually on disk there (git log/diff on that optimizer.py, or rebuild/reinstall from the real v6.0.6 tag) rather than treating this as something to fix in the addon.

**Comment by jralls** [comment]
A quick grep of the tarballs used to build the Mac bundles shows Claude is correct: ` rules_with_selected_handles` last appeared in gramps-6.0.1 from April of last year. The release Mac bundles are built from the tarballs, there should be no git version issues.

**Comment by GaryGriffin** [comment]
D'ohhhh. Unittests are run against the local build, and in my case is 6.0.1 .
Sorry for the waste of time. I need to update my local build to run unittests
