### PR TITLE
GoogleMapXML fix 2 errors[gramps50]

### PR DESCRIPTION
**Pull request by sam-m888**
Mentioned in comment https://github.com/gramps-project/addons-source/pull/109#issuecomment-365806328  reported by @adamvazquez82 thank you.

fixes:

> 2018-02-14 15:21:27.187: WARNING: _manager.py: line 295: Plugin error (from 'GoogleEarthWriteKML'): cannot import name 'conv_to_unicode'

and found the second issue:

> TypeError: open_file_with_default_application() missing 1 required positional argument: 'uistate'

### CODE REVIEW

**Comment by sam-m888** [comment]
@adamvazquez82 Addon rebuilt please update your addon.

> Also separate to this but related; the GoogleMapKML addon does not work on 4.2.6 (creates an empty xml place file) and on the newest 5.0 alpha3 from @bpisoj I get

Please note that this does not fix empty xml file that I believe you are referring to the  "GrampsPlacesForGoogleEarth.kml" file?

**Comment by sam-m888** [comment]
A closer look at the code showed that if a Place did not have a set of coordinates (latitude/longitude) it was silent skipped.  To show that this is happening I've added in PR https://github.com/gramps-project/addons-source/pull/111 logging to show a warning that the place has been skipped. So technically the empty file was not empty it only did not have a location to display.

Please update the addon.

**Comment by adamvazquez82** [comment]
That worked 👍    Turns out I have a lot of Coordinates to add !!!!

Thanks
